const pedidos =
    [
        { "id": 1, "cantidad": 2, "cliente": "example 1", "detalle": "{\"hidden_nombre\":\"Milanesa comun (sin Aji)\",\"hidden_precio\":650,\"hidden_cant\":1,\"hidden_clase\":\"panSan\"},{\"hidden_nombre\":\"napolitana\",\"hidden_precio\":750,\"hidden_cant\":1,\"hidden_clase\":\"pPapas\"}", "importe": 1400, "detalleTicket": "1 Milanesa comun (sin Aji)<br><br>1 napolitana<br><br>", "statu": "", "pj": 0, "pagado": 0 },
        { "id": 2, "cantidad": 2, "cliente": "example 2", "detalle": "{\"hidden_nombre\":\"pizza comun\",\"hidden_precio\":650,\"hidden_cant\":1,\"hidden_clase\":\"pPizzas\"},{\"hidden_nombre\":\"salchipapas\",\"hidden_precio\":500,\"hidden_cant\":1,\"hidden_clase\":\"pPapas\"}", "importe": 1150, "detalleTicket": "1 pizza comun<br><br>1 salchipapas<br><br>", "statu": "", "pj": 0, "pagado": 0 },
        { "id": 3, "cantidad": 1, "cliente": "example 3", "detalle": "{\"hidden_nombre\":\"Lomito esp. de fiambre (sin Savora), (sin Lechuga), (sin Aji)\",\"hidden_precio\":900,\"hidden_cant\":1,\"hidden_clase\":\"panSan\"}", "importe": 900, "detalleTicket": "1 Lomito esp. de fiambre (sin Savora), (sin Lechuga), (sin Aji)<br><br>", "statu": "", "pj": 0, "pagado": 0 },
        { "id": 4, "cantidad": 3, "cliente": "example 4", "detalle": "{\"hidden_nombre\":\"Milanesa esp. de fiambre (sin Tomate), (sin Aji)\",\"hidden_precio\":800,\"hidden_cant\":1,\"hidden_clase\":\"panSan\"},{\"hidden_nombre\":\"Milanesa comun (completa) \",\"hidden_precio\":650,\"hidden_cant\":1,\"hidden_clase\":\"panSan\"},{\"hidden_nombre\":\"pepsi 2L\",\"hidden_precio\":400,\"hidden_cant\":1,\"hidden_clase\":\"\"}", "importe": 1850, "detalleTicket": "1 Milanesa esp. de fiambre (sin Tomate), (sin Aji)<br><br>1 Milanesa comun (completa) <br><br>1 pepsi 2L<br><br>", "statu": "", "pj": 0, "pagado": 0 }
    ]

const milanesasDB = [{ "id": 1, "nombre": "milanesa comun", "precio": 800 }, { "id": 2, "nombre": "milanesa esp. fiambre", "precio": 1000 }, { "id": 3, "nombre": "milanesa esp. papas", "precio": 1000 }]
const lomitosDB =
    [{ "id": 1, "nombre": "lomito comun", "precio": 1000 }, { "id": 2, "nombre": "lomito esp. fiambre", "precio": 1200 }, { "id": 3, "nombre": "lomito esp. papas", "precio": 1200 }]
const hamburguesasDB = [{ "id": 1, "nombre": "junior comun", "precio": 600 }, { "id": 2, "nombre": "junior especial", "precio": 700 }, { "id": 3, "nombre": "mega comun", "precio": 1100 }, { "id": 4, "nombre": "mega esp. fiambre", "precio": 1400 }, { "id": 5, "nombre": "mega esp. papas", "precio": 1400 }]
const papasDB = [{ "id": 1, "nombre": "papas comun", "precio": 500 }, { "id": 2, "nombre": "papas gratinadas", "precio": 600 }, { "id": 3, "nombre": "salchipapas", "precio": 500 }]
const pizzasDB = [{ "id": 1, "nombre": "pizza comun", "precio": 900 }, { "id": 2, "nombre": "pizza esp. de jamon", "precio": 1000 }, { "id": 3, "nombre": "pizza fugazza", "precio": 900 }, { "id": 4, "nombre": "pizza calabresa", "precio": 1000 }, { "id": 5, "nombre": "pizza napolitana", "precio": 1000 }, { "id": 6, "nombre": "pizza con sardina", "precio": 900 }, { "id": 7, "nombre": "pizzanesa p4", "precio": 3000 }, { "id": 8, "nombre": "pizzanesa p2", "precio": 2000 }, { "id": 9, "nombre": "media pizza comun", "precio": 450 }, { "id": 10, "nombre": "media pizza esp. jamon", "precio": 500 }, { "id": 11, "nombre": "media pizza fugazza", "precio": 450 }, { "id": 12, "nombre": "media pizza calabresa", "precio": 500 }, { "id": 13, "nombre": "media pizza napolitana", "precio": 500 }, { "id": 14, "nombre": "media pizza sardina", "precio": 0 }]
const platosDB = [{ "id": 1, "nombre": "lomito al plato", "precio": 1200 }, { "id": 2, "nombre": "napolitana", "precio": 1100 }, { "id": 3, "nombre": "milanesa a caballo", "precio": 1100 }, { "id": 4, "nombre": "mexicano p1", "precio": 1100 }, { "id": 5, "nombre": "mexicano p2", "precio": 2000 }, { "id": 6, "nombre": "napolitana c/ensalada", "precio": 2000 }, { "id": 7, "nombre": "milanesa c/ensalada", "precio": 1100 }]
const bebidasDB = [{ "id": 1, "nombre": "pepsi 2L", "precio": 450 }, { "id": 2, "nombre": "pepsi 1.25L", "precio": 200 }, { "id": 3, "nombre": "mirinda 2L", "precio": 450 }, { "id": 4, "nombre": "secco 2L", "precio": 250 }, { "id": 5, "nombre": "coca 1.5L", "precio": 450 }, { "id": 6, "nombre": "jugo fresh", "precio": 200 }, { "id": 7, "nombre": "vaso de gaseosa", "precio": 300 }]